apiVersion: v2
name: ingest
description: HL7 v2 receiver for the NHS Interop Platform.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords: [nhs, interop, hl7, fhir]
maintainers:
  - name: platform-engineering
